### PR TITLE
dualwield support

### PR DESCRIPTION
**Pull request by abdulkadiraktas**
add dataview
add dualwield

### CODE REVIEW

**Comment by outsider31000** [comment]
this is a copy from a conversion to Lua made by the VORP team devs, where are the credits for the original author?
last time I remember you came to cry for the same reason, and now you doing the same?  so please give the proper credits.

**Comment by outsider31000** [comment]
image

**Comment by abdulkadiraktas** [comment]
No, I converted it myself. I am not ignorant enough to copy what other people do. :D

**Comment by outsider31000** [comment]
It's a copy  https://pastebin.com/QqiQFzK2 give original credit.

**Comment by abdulkadiraktas** [comment]
I think you will keep crying. You can cry all you want.

**Comment by outsider31000** [comment]
youre the one who came crying. now you doing the same. this is your last warning.

**Comment by abdulkadiraktas** [comment]
I don't know who you think you are, but I just saw the link you mentioned and I created this code before. This code has nothing to do with the link you sent. All credits to "disquse".

**Comment by outsider31000** [comment]
the link has been shared all over the place stop lying

**Comment by outsider31000** [comment]
you came crying now yo u doing the same next time dont cry then.

**Comment by abdulkadiraktas** [comment]
I think you're confusing me with yourself. Like I said, I'm not ignorant enough to copy anyone's code.  I converted and used this code when it shared "disquse".

If you look at the screenshot, you can see that I used it before it was shared by you.

http://prntscr.com/7Dl11l_M1DOg

Now you can believe what you want. But I converted this code myself.

**Comment by abdulkadiraktas** [comment]
image

Let me add this here so that no one has a question mark in mind.

**Comment by outsider31000** [comment]
are you calling me ignorant?

**Comment by abdulkadiraktas** [comment]
Are you?

**Comment by egerdnc** [comment]
Its the exact same code but beautified 🤣🤣🤣

**Pull request closed without merging**
